version: '2.15'
services:
    postgresdb:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=admin
            
    adminer:
        image: adminer
        ports:
            - 8080:8080
        restart: always
